/* Generated By:JavaCC: Do not edit this line. OO2ParserConstants.java */
package loo2.plp.orientadaObjetos2.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OO2ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int LENGTH = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int ELVIS = 15;
  /** RegularExpression Id. */
  int SAFE_DOT = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int COMAND_SKIP = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int READ = 21;
  /** RegularExpression Id. */
  int WRITE = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int THEN = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int NEW = 26;
  /** RegularExpression Id. */
  int THIS = 27;
  /** RegularExpression Id. */
  int CLASSE = 28;
  /** RegularExpression Id. */
  int NULL = 29;
  /** RegularExpression Id. */
  int PROC = 30;
  /** RegularExpression Id. */
  int EXTENDS = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int BOOLEAN = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 35;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 36;
  /** RegularExpression Id. */
  int HEX_LITERAL = 37;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 38;
  /** RegularExpression Id. */
  int STRING_LITERAL = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int LETTER = 41;
  /** RegularExpression Id. */
  int DIGIT = 42;
  /** RegularExpression Id. */
  int LPAREN = 43;
  /** RegularExpression Id. */
  int RPAREN = 44;
  /** RegularExpression Id. */
  int LBRACE = 45;
  /** RegularExpression Id. */
  int RBRACE = 46;
  /** RegularExpression Id. */
  int LBRACKET = 47;
  /** RegularExpression Id. */
  int RBRACKET = 48;
  /** RegularExpression Id. */
  int SEMICOLON = 49;
  /** RegularExpression Id. */
  int COMMA = 50;
  /** RegularExpression Id. */
  int DOT = 51;
  /** RegularExpression Id. */
  int ATTRIB = 52;
  /** RegularExpression Id. */
  int ASSIGN = 53;
  /** RegularExpression Id. */
  int GT = 54;
  /** RegularExpression Id. */
  int LT = 55;
  /** RegularExpression Id. */
  int BANG = 56;
  /** RegularExpression Id. */
  int TILDE = 57;
  /** RegularExpression Id. */
  int HOOK = 58;
  /** RegularExpression Id. */
  int COLON = 59;
  /** RegularExpression Id. */
  int EQ = 60;
  /** RegularExpression Id. */
  int LE = 61;
  /** RegularExpression Id. */
  int GE = 62;
  /** RegularExpression Id. */
  int NE = 63;
  /** RegularExpression Id. */
  int SC_OR = 64;
  /** RegularExpression Id. */
  int SC_AND = 65;
  /** RegularExpression Id. */
  int CONCAT = 66;
  /** RegularExpression Id. */
  int PLUS = 67;
  /** RegularExpression Id. */
  int MINUS = 68;
  /** RegularExpression Id. */
  int STAR = 69;
  /** RegularExpression Id. */
  int SLASH = 70;
  /** RegularExpression Id. */
  int BIT_AND = 71;
  /** RegularExpression Id. */
  int BIT_OR = 72;
  /** RegularExpression Id. */
  int XOR = 73;
  /** RegularExpression Id. */
  int REM = 74;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"?:\"",
    "\"?.\"",
    "\"var\"",
    "\"skip\"",
    "\"while\"",
    "\"do\"",
    "\"read\"",
    "\"write\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"new\"",
    "\"this\"",
    "\"classe\"",
    "\"null\"",
    "\"proc\"",
    "\"extends\"",
    "\"int\"",
    "\"boolean\"",
    "\"string\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":=\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
  };

}
